name: scrape

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 16 * * 3' # should be once a week, on Wednesdays, at 11am ET
jobs:
  scrape:
    runs-on: ubuntu-20.04
    services:
      selenium:
        image: selenium/standalone-firefox:2.53.1
        ports:
          - 4444:4444
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        r-version: '4.0.4'
    - uses: r-lib/actions/setup-renv@v2
    - name: Fetch latest data and send alerts
      run: |-
        Rscript scrape/scrape.R
      env:
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        NOTIFY_SLACK: TRUE
    - name: Commit new files
      run: |-
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/raw/*
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
